import {
  FileText,
  Search,
  GitBranch,
  Bug,
  Settings,
  Terminal,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  X,
  Plus,
  Save,
  Folder,
  File,
  Code,
  Type,
  FileJson,
  FileImage,
  FileVideo,
  FileAudio,
  FileArchive,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  FolderCheck,
  FolderX,
  FolderGit,
  FolderGit2,
  FolderSearch,
  FolderHeart,
  FolderLock,
  FolderKey,
  FolderCog,
} from 'lucide-react';

export const ICONS = {
  // 活动栏图标
  EXPLORER: FileText,
  SEARCH: Search,
  GIT: GitBranch,
  DEBUG: Bug,
  SETTINGS: Settings,
  TERMINAL: Terminal,

  // 面板控制图标
  CHEVRON_UP: ChevronUp,
  CHEVRON_DOWN: ChevronDown,
  CHEVRON_LEFT: ChevronLeft,
  CHEVRON_RIGHT: ChevronRight,
  CLOSE: X,
  ADD: Plus,
  SAVE: Save,

  // 文件类型图标
  FOLDER: Folder,
  FILE: File,
  CODE: Code,
  TYPESCRIPT: Type,
  JSON: FileJson,
  MARKDOWN: FileText,
  IMAGE: FileImage,
  VIDEO: FileVideo,
  AUDIO: FileAudio,
  ARCHIVE: FileArchive,

  // 文件夹状态图标
  FOLDER_OPEN: FolderOpen,
  FOLDER_PLUS: FolderPlus,
  FOLDER_MINUS: FolderMinus,
  FOLDER_CHECK: FolderCheck,
  FOLDER_X: FolderX,
  FOLDER_GIT: FolderGit,
  FOLDER_GIT2: FolderGit2,
  FOLDER_SEARCH: FolderSearch,
  FOLDER_HEART: FolderHeart,
  FOLDER_LOCK: FolderLock,
  FOLDER_KEY: FolderKey,
  FOLDER_COG: FolderCog,
} as const;

export type IconKey = keyof typeof ICONS; 